### ISSUE TITLE
Antwortfeld

### ISSUE THREAD

**Issue by chamabreu** [pquandt/msgberry#5]
Soll beim senden gefuellt werden mit der Frage.
Diese "dummy funktion" wird spaeter gebraucht um daten vom backend da reinzuschmeissen.

**Comment by pquandt** [comment]
Jo, da hab ich noch überhaupt gar keine Ahnung , dass wird dauern.

**Comment by chamabreu** [comment]
[https://github.com/pquandt/msgberry/commit/cd1d4e9382845bad8e482fb4699854fe3b2c53a7](url)
Hab da ein Todo reingeschmissen mit denkanstoessen

**Comment by pquandt** [comment]
tut es
