### ISSUE TITLE
DarkModeSwitcher

### ISSUE THREAD

**Issue by chamabreu** [pquandt/msgberry#7]
Soll immer das gegenteil anzeigen.

Wenn Light mode, dann soll da der Mond erscheinen, wenn dark mode dann die sonne.

**Comment by pquandt** [comment]
Das ist nur ein Platzhalter. Da soll noch n richtig schöner switch hin. darktheme war eignetlich auch schon fertig, aber hab ich verbaselt...Theme context datei is wieder drin. muss ich nur die tage neu verknüpfen.

**Comment by pquandt** [comment]
schöner switch is drin und switched. bisher nur background. kann man noch ändern wenn ich weiß was noch so kommt.
