### ISSUE TITLE
Options nummerieren

### ISSUE THREAD

**Issue by chamabreu** [pquandt/msgberry#8]
Die Options brauchen am einfache aufsteigende nummern und keine uuids.
Die Optionfelder sollen dann als Placeholder `Option 1` `Option 2` usw haben

**Comment by pquandt** [comment]
jo. irgendwo muss man die id hochzählen lassen. muss ich noch finden. text is erstma drin...heißt jetzt halt immer 1...

**Comment by chamabreu** [comment]
#4 Wird da mit zusammenhängen.
Einfach eine counter variable als state auf die sich die Optionfelder beziehen vielleicht.

**Comment by pquandt** [comment]
done
